name: Build and deploy this site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: ruby/setup-ruby
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: '18'
      - run: npm install
      - name: Build site
        uses: limjh16/jekyll-action-ts
        with:
          enable_cache: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages
        with:
          github_token: $
          publish_dir: ./_site